server:
  port: 9411

spring:
  application:
    name: hello-spring-cloud-zipkin


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  metrics:
    web:
      server:
        auto-time-requests: false